### ISSUE TITLE
Hvordan lage en norsk versjon av creeper?

### ISSUE THREAD

**Issue by graabein** [pawal/creeperwikipedia#1]
Heisann.  Usikker på hvor jeg kan kontakte deg, så slenger inn en forespørsel her.  Hvordan kan vi få til en norsk versjon av creeper, så vi får overvåket våre egne overvåkere?

**Comment by pawal** [comment]
Hej!
Du når mig på pawal@blipp.com
PGP: 3090 0C4F 6941 FB6A ADFE  0A78 DBFF E2D7 B762 49F2
